MusicBundle:
    resource: "@MusicBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: MusicBundle:Music:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"